nodefy -o cjs "src/**.js"
nodefy -o cjs/api "src/api/**.js"
nodefy -o cjs/plugins/core "src/plugins/core/**.js"
nodefy -o cjs/plugins/core/commands "src/plugins/core/commands/**.js"
nodefy -o cjs/plugins/core/formatters/html "src/plugins/core/formatters/html/**.js"
nodefy -o cjs/plugins/core/formatters/plain-text "src/plugins/core/formatters/plain-text/**.js"
nodefy -o cjs/plugins/core/patches "src/plugins/core/patches/**.js"
nodefy -o cjs/plugins/core/patches/commands "src/plugins/core/patches/commands/**.js"